/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Glory_Schema;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author Yaas
 */
public class MainFrame extends javax.swing.JFrame {

    FunctionElement functionObj;
    int round=1;
    String playerName;
    int playerCount=0;
    
    public MainFrame() {
        initComponents();
        
        panelParent.removeAll();
        panelParent.add(panelMain);
     // panelParent.add(panelGame);
        panelParent.repaint();
        panelParent.revalidate();
        
        generateFirst3Letters();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        btnPlayNow = new javax.swing.JButton();
        btnHowToPlay = new javax.swing.JButton();
        btnHighScores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelStart = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPlayerName = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnJoin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPlayersConnected = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JLabel();
        panelGame = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        p2Letter1 = new javax.swing.JLabel();
        p2Letter2 = new javax.swing.JLabel();
        p2Letter3 = new javax.swing.JLabel();
        p2Letter4 = new javax.swing.JLabel();
        p2Letter5 = new javax.swing.JLabel();
        p2Letter6 = new javax.swing.JLabel();
        p2Letter7 = new javax.swing.JLabel();
        p2Letter8 = new javax.swing.JLabel();
        p2Letter9 = new javax.swing.JLabel();
        p2Letter10 = new javax.swing.JLabel();
        p2Letter11 = new javax.swing.JLabel();
        p1Letter1 = new javax.swing.JLabel();
        p1Letter2 = new javax.swing.JLabel();
        p1Letter3 = new javax.swing.JLabel();
        p1Letter4 = new javax.swing.JLabel();
        p1Letter5 = new javax.swing.JLabel();
        p1Letter6 = new javax.swing.JLabel();
        p1Letter7 = new javax.swing.JLabel();
        p1Letter8 = new javax.swing.JLabel();
        p1Letter9 = new javax.swing.JLabel();
        p1Letter10 = new javax.swing.JLabel();
        p1Letter11 = new javax.swing.JLabel();
        p1Letter12 = new javax.swing.JLabel();
        p1Letter13 = new javax.swing.JLabel();
        p1Letter14 = new javax.swing.JLabel();
        p1Letter15 = new javax.swing.JLabel();
        p1Letter16 = new javax.swing.JLabel();
        p1Letter17 = new javax.swing.JLabel();
        p1Letter18 = new javax.swing.JLabel();
        p1Letter19 = new javax.swing.JLabel();
        p1Letter20 = new javax.swing.JLabel();
        p1Letter21 = new javax.swing.JLabel();
        p1Letter22 = new javax.swing.JLabel();
        p1Letter23 = new javax.swing.JLabel();
        p1Letter24 = new javax.swing.JLabel();
        p1Letter25 = new javax.swing.JLabel();
        p1Letter26 = new javax.swing.JLabel();
        p1Letter27 = new javax.swing.JLabel();
        p1Letter28 = new javax.swing.JLabel();
        p1Letter29 = new javax.swing.JLabel();
        p1Letter30 = new javax.swing.JLabel();
        p1Letter31 = new javax.swing.JLabel();
        p1Letter32 = new javax.swing.JLabel();
        p1Letter33 = new javax.swing.JLabel();
        btnP2_8C = new javax.swing.JButton();
        btnP2_4V = new javax.swing.JButton();
        btnP2_4C = new javax.swing.JButton();
        btnP2_5V = new javax.swing.JButton();
        btnP2_5C = new javax.swing.JButton();
        btnP2_6V = new javax.swing.JButton();
        btnP2_6C = new javax.swing.JButton();
        btnP2_7V = new javax.swing.JButton();
        btnP2_7C = new javax.swing.JButton();
        btnP2_9V = new javax.swing.JButton();
        btnP2_9C = new javax.swing.JButton();
        btnP2_10V = new javax.swing.JButton();
        btnP2_10C = new javax.swing.JButton();
        btnP2_11V = new javax.swing.JButton();
        btnP2_11C = new javax.swing.JButton();
        p1Letter34 = new javax.swing.JLabel();
        p1Letter37 = new javax.swing.JLabel();
        lblScoreP2 = new javax.swing.JLabel();
        p1Letter39 = new javax.swing.JLabel();
        txtFinalWordP2 = new javax.swing.JTextField();
        lblScoreP1 = new javax.swing.JLabel();
        btnP2_8V1 = new javax.swing.JButton();
        btnSubmitP2 = new javax.swing.JButton();
        lblScoreP3 = new javax.swing.JLabel();
        lblScoreP4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParent.setMinimumSize(new java.awt.Dimension(0, 0));
        panelParent.setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(44, 62, 80));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlayNow.setBackground(new java.awt.Color(44, 62, 80));
        btnPlayNow.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnPlayNow.setForeground(new java.awt.Color(236, 240, 241));
        btnPlayNow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/puzzle (1).png"))); // NOI18N
        btnPlayNow.setText(" Play Now");
        btnPlayNow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayNow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayNowActionPerformed(evt);
            }
        });
        panelMain.add(btnPlayNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 260, 286));

        btnHowToPlay.setBackground(new java.awt.Color(44, 62, 80));
        btnHowToPlay.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnHowToPlay.setForeground(new java.awt.Color(236, 240, 241));
        btnHowToPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/problems.png"))); // NOI18N
        btnHowToPlay.setText("How To PLay");
        btnHowToPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHowToPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMain.add(btnHowToPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 260, 286));

        btnHighScores.setBackground(new java.awt.Color(44, 62, 80));
        btnHighScores.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnHighScores.setForeground(new java.awt.Color(236, 240, 241));
        btnHighScores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/scoreboard.png"))); // NOI18N
        btnHighScores.setText("High Scores");
        btnHighScores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHighScores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMain.add(btnHighScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 260, 286));

        jLabel2.setBackground(new java.awt.Color(52, 73, 94));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Glory Game");
        jLabel2.setOpaque(true);
        panelMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 140));

        panelParent.add(panelMain, "card3");

        panelStart.setBackground(new java.awt.Color(44, 62, 80));
        panelStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(236, 240, 241));
        jSeparator2.setForeground(new java.awt.Color(236, 240, 241));
        panelStart.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, 370, 20));

        txtPlayerName.setBackground(new java.awt.Color(44, 62, 80));
        txtPlayerName.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtPlayerName.setForeground(new java.awt.Color(236, 240, 241));
        txtPlayerName.setBorder(null);
        txtPlayerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayerNameActionPerformed(evt);
            }
        });
        panelStart.add(txtPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 360, 50));

        txtPlayer2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtPlayer2.setForeground(new java.awt.Color(236, 240, 241));
        txtPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlayer2.setText("Player 2");
        panelStart.add(txtPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 420, 30));

        btnPlay.setBackground(new java.awt.Color(236, 240, 241));
        btnPlay.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(44, 62, 80));
        btnPlay.setText("Play Now");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        panelStart.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 190, 40));

        jLabel3.setBackground(new java.awt.Color(52, 73, 94));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Glory Game");
        jLabel3.setOpaque(true);
        panelStart.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/chip (1).png"))); // NOI18N
        panelStart.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 560, 560));

        btnJoin.setBackground(new java.awt.Color(236, 240, 241));
        btnJoin.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnJoin.setForeground(new java.awt.Color(44, 62, 80));
        btnJoin.setText("Join");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        panelStart.add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 130, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Player Name");
        panelStart.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 240, 50));

        txtPlayersConnected.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtPlayersConnected.setForeground(new java.awt.Color(236, 240, 241));
        txtPlayersConnected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlayersConnected.setText("Number of players connected - 0");
        panelStart.add(txtPlayersConnected, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 420, 50));

        txtPlayer1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtPlayer1.setForeground(new java.awt.Color(236, 240, 241));
        txtPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlayer1.setText("Player 1");
        panelStart.add(txtPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 420, 30));

        panelParent.add(panelStart, "card4");

        panelGame.setMinimumSize(new java.awt.Dimension(1400, 700));
        panelGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelGame.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 350, 1400, 10));

        p2Letter1.setBackground(new java.awt.Color(204, 204, 204));
        p2Letter1.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter1.setText("A");
        p2Letter1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2Letter1.setOpaque(true);
        panelGame.add(p2Letter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 100, 90));

        p2Letter2.setBackground(new java.awt.Color(204, 204, 204));
        p2Letter2.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter2.setText("A");
        p2Letter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2Letter2.setOpaque(true);
        panelGame.add(p2Letter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 100, 90));

        p2Letter3.setBackground(new java.awt.Color(204, 204, 204));
        p2Letter3.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter3.setText("A");
        p2Letter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2Letter3.setOpaque(true);
        panelGame.add(p2Letter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 100, 90));

        p2Letter4.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p2Letter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 100, 90));

        p2Letter5.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p2Letter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 100, 90));

        p2Letter6.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p2Letter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 100, 90));

        p2Letter7.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p2Letter7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 100, 90));

        p2Letter8.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p2Letter8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 100, 90));

        p2Letter9.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p2Letter9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 460, 100, 90));

        p2Letter10.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p2Letter10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 460, 100, 90));

        p2Letter11.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p2Letter11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p2Letter11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 460, 100, 90));

        p1Letter1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        p1Letter1.setText("PLAYER 2 : Zacky");
        panelGame.add(p1Letter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 310, 40));

        p1Letter2.setBackground(new java.awt.Color(204, 204, 204));
        p1Letter2.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter2.setText("A");
        p1Letter2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1Letter2.setOpaque(true);
        panelGame.add(p1Letter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 90));

        p1Letter3.setBackground(new java.awt.Color(204, 204, 204));
        p1Letter3.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter3.setText("A");
        p1Letter3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1Letter3.setOpaque(true);
        panelGame.add(p1Letter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 90, 90));

        p1Letter4.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter4.setText("?");
        p1Letter4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p1Letter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 90, 90));

        p1Letter5.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter5.setText("?");
        p1Letter5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p1Letter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 90, 90));

        p1Letter6.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter6.setText("?");
        p1Letter6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p1Letter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 90, 90));

        p1Letter7.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter7.setText("?");
        p1Letter7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p1Letter7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 90, 90));

        p1Letter8.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter8.setText("?");
        p1Letter8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p1Letter8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 90, 90));

        p1Letter9.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter9.setText("?");
        p1Letter9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p1Letter9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 90, 90));

        p1Letter10.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter10.setText("?");
        p1Letter10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p1Letter10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 100, 90, 90));

        p1Letter11.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter11.setText("?");
        p1Letter11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(p1Letter11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 100, 90, 90));

        p1Letter12.setBackground(new java.awt.Color(204, 204, 204));
        p1Letter12.setFont(new java.awt.Font("Century Gothic", 0, 70)); // NOI18N
        p1Letter12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter12.setText("A");
        p1Letter12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1Letter12.setOpaque(true);
        panelGame.add(p1Letter12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 90));

        p1Letter13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter13.setText("1");
        panelGame.add(p1Letter13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 40, 30));

        p1Letter14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter14.setText("2");
        panelGame.add(p1Letter14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 40, 30));

        p1Letter15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter15.setText("3");
        panelGame.add(p1Letter15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 40, 30));

        p1Letter16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter16.setText("4");
        panelGame.add(p1Letter16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 40, 30));

        p1Letter17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter17.setText("5");
        panelGame.add(p1Letter17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 40, 30));

        p1Letter18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter18.setText("6");
        panelGame.add(p1Letter18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 40, 30));

        p1Letter19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter19.setText("7");
        panelGame.add(p1Letter19, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 40, 30));

        p1Letter20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter20.setText("1");
        panelGame.add(p1Letter20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 40, 30));

        p1Letter21.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter21.setText("2");
        panelGame.add(p1Letter21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 40, 30));

        p1Letter22.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter22.setText("3");
        panelGame.add(p1Letter22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 40, 30));

        p1Letter23.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter23.setText("4");
        panelGame.add(p1Letter23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 40, 30));

        p1Letter24.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter24.setText("5");
        panelGame.add(p1Letter24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 40, 30));

        p1Letter25.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter25.setText("8");
        panelGame.add(p1Letter25, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 40, 30));

        p1Letter26.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter26.setText("9");
        panelGame.add(p1Letter26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 60, 40, 30));

        p1Letter27.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter27.setText("10");
        panelGame.add(p1Letter27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 60, 40, 30));

        p1Letter28.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter28.setText("6");
        panelGame.add(p1Letter28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 40, 30));

        p1Letter29.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter29.setText("7");
        panelGame.add(p1Letter29, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 40, 30));

        p1Letter30.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter30.setText("8");
        panelGame.add(p1Letter30, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 40, 30));

        p1Letter31.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter31.setText("9");
        panelGame.add(p1Letter31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 40, 30));

        p1Letter32.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter32.setText("10");
        panelGame.add(p1Letter32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 420, 40, 30));

        p1Letter33.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter33.setText("11");
        panelGame.add(p1Letter33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 420, 40, 30));

        btnP2_8C.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_8C.setText("Consonant");
        btnP2_8C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_8CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_8C, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 100, 30));

        btnP2_4V.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_4V.setText("Vowel");
        btnP2_4V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_4VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_4V, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 100, 30));

        btnP2_4C.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_4C.setText("Consonant");
        btnP2_4C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_4CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_4C, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 100, 30));

        btnP2_5V.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_5V.setText("Vowel");
        btnP2_5V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_5VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_5V, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 100, 30));

        btnP2_5C.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_5C.setText("Consonant");
        btnP2_5C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_5CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_5C, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 100, 30));

        btnP2_6V.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_6V.setText("Vowel");
        btnP2_6V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_6VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_6V, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 100, 30));

        btnP2_6C.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_6C.setText("Consonant");
        btnP2_6C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_6CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_6C, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 100, 30));

        btnP2_7V.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_7V.setText("Vowel");
        btnP2_7V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_7VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_7V, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 100, 30));

        btnP2_7C.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_7C.setText("Consonant");
        btnP2_7C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_7CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_7C, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 100, 30));

        btnP2_9V.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_9V.setText("Vowel");
        btnP2_9V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_9VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_9V, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 560, 100, 30));

        btnP2_9C.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_9C.setText("Consonant");
        btnP2_9C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_9CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_9C, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 600, 100, 30));

        btnP2_10V.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_10V.setText("Vowel");
        btnP2_10V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_10VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_10V, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 560, 100, 30));

        btnP2_10C.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_10C.setText("Consonant");
        btnP2_10C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_10CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_10C, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 600, 100, 30));

        btnP2_11V.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_11V.setText("Vowel");
        btnP2_11V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_11VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_11V, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 560, 100, 30));

        btnP2_11C.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_11C.setText("Consonant");
        btnP2_11C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_11CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_11C, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 600, 100, 30));

        p1Letter34.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1Letter34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter34.setText("11");
        panelGame.add(p1Letter34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 60, 40, 30));

        p1Letter37.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        p1Letter37.setText("PLAYER 1 : Adam");
        panelGame.add(p1Letter37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 40));

        lblScoreP2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblScoreP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreP2.setText("Round : 1/5");
        lblScoreP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(lblScoreP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 120, 30));

        p1Letter39.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        p1Letter39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter39.setText("Final Word");
        panelGame.add(p1Letter39, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 660, 130, 30));

        txtFinalWordP2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtFinalWordP2.setToolTipText("Final Word");
        txtFinalWordP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalWordP2ActionPerformed(evt);
            }
        });
        panelGame.add(txtFinalWordP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, 300, 30));

        lblScoreP1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblScoreP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreP1.setText("Score : 0");
        lblScoreP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(lblScoreP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 110, 30));

        btnP2_8V1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnP2_8V1.setText("Vowel");
        btnP2_8V1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_8V1ActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_8V1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 100, 30));

        btnSubmitP2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnSubmitP2.setText("Submit");
        btnSubmitP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitP2ActionPerformed(evt);
            }
        });
        panelGame.add(btnSubmitP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 660, 100, 30));

        lblScoreP3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblScoreP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreP3.setText("Score : 0");
        lblScoreP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(lblScoreP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 360, 110, 30));

        lblScoreP4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblScoreP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScoreP4.setText("Round : 1/5");
        lblScoreP4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGame.add(lblScoreP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 360, 120, 30));

        panelParent.add(panelGame, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnP2_8CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_8CActionPerformed
        char consonant=functionObj.generateConsonant();
        p2Letter8.setText(String.valueOf(consonant));
    }//GEN-LAST:event_btnP2_8CActionPerformed

    private void btnP2_4CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_4CActionPerformed
        char consonant=functionObj.generateConsonant();
        p2Letter4.setText(String.valueOf(consonant));
    }//GEN-LAST:event_btnP2_4CActionPerformed

    private void btnP2_5CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_5CActionPerformed
        char consonant=functionObj.generateConsonant();
        p2Letter5.setText(String.valueOf(consonant));
    }//GEN-LAST:event_btnP2_5CActionPerformed

    private void btnP2_6CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_6CActionPerformed
        char consonant=functionObj.generateConsonant();
        p2Letter6.setText(String.valueOf(consonant));
    }//GEN-LAST:event_btnP2_6CActionPerformed

    private void btnP2_7CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_7CActionPerformed
        char consonant=functionObj.generateConsonant();
        p2Letter7.setText(String.valueOf(consonant));
    }//GEN-LAST:event_btnP2_7CActionPerformed

    private void btnP2_9CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_9CActionPerformed
        char consonant=functionObj.generateConsonant();
        p2Letter9.setText(String.valueOf(consonant));
    }//GEN-LAST:event_btnP2_9CActionPerformed

    private void btnP2_10CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_10CActionPerformed
        char consonant=functionObj.generateConsonant();
        p2Letter10.setText(String.valueOf(consonant));
    }//GEN-LAST:event_btnP2_10CActionPerformed

    private void btnP2_11CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_11CActionPerformed
        char consonant=functionObj.generateConsonant();
        p2Letter11.setText(String.valueOf(consonant));
    }//GEN-LAST:event_btnP2_11CActionPerformed

    private void txtFinalWordP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalWordP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinalWordP2ActionPerformed

    private void btnSubmitP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitP2ActionPerformed
        String UserFinalWord;
        UserFinalWord=txtFinalWordP2.getText();
        
        GloryElement wordObj = new GloryElement();
        wordObj.setFinalWord(UserFinalWord);
        wordObj.setFinalWordLength();
        functionObj = new FunctionElement();
        functionObj.generateScore();
        
        ServerElement serverObj = new ServerElement(playerName,round, functionObj.rarenessScore, functionObj.rewardScore, functionObj.wordLengthScore, functionObj.finalScore);
        
        round++;
        
        
    }//GEN-LAST:event_btnSubmitP2ActionPerformed

    private void btnP2_4VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_4VActionPerformed
        char vowel=functionObj.generateVowel();
        p2Letter4.setText(String.valueOf(vowel));
    }//GEN-LAST:event_btnP2_4VActionPerformed

    private void btnP2_5VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_5VActionPerformed
        char vowel=functionObj.generateVowel();
        p2Letter5.setText(String.valueOf(vowel));
    }//GEN-LAST:event_btnP2_5VActionPerformed

    private void btnP2_6VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_6VActionPerformed
        char vowel=functionObj.generateVowel();
        p2Letter6.setText(String.valueOf(vowel));
    }//GEN-LAST:event_btnP2_6VActionPerformed

    private void btnP2_7VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_7VActionPerformed
        char vowel=functionObj.generateVowel();
        p2Letter7.setText(String.valueOf(vowel));
    }//GEN-LAST:event_btnP2_7VActionPerformed

    private void btnP2_8V1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_8V1ActionPerformed
        char vowel=functionObj.generateVowel();
        p2Letter8.setText(String.valueOf(vowel));
    }//GEN-LAST:event_btnP2_8V1ActionPerformed

    private void btnP2_9VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_9VActionPerformed
        char vowel=functionObj.generateVowel();
        p2Letter9.setText(String.valueOf(vowel));
    }//GEN-LAST:event_btnP2_9VActionPerformed

    private void btnP2_10VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_10VActionPerformed
        char vowel=functionObj.generateVowel();
        p2Letter10.setText(String.valueOf(vowel));
    }//GEN-LAST:event_btnP2_10VActionPerformed

    private void btnP2_11VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_11VActionPerformed
       char vowel=functionObj.generateVowel();
        p2Letter11.setText(String.valueOf(vowel));
    }//GEN-LAST:event_btnP2_11VActionPerformed

    private void btnPlayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayNowActionPerformed
        panelParent.removeAll();
        panelParent.add(panelStart);
        panelParent.repaint();
        panelParent.revalidate();
        
         
        btnPlay.setEnabled(false);
    
    }//GEN-LAST:event_btnPlayNowActionPerformed

    private void txtPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerNameActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        panelParent.removeAll();
        panelParent.add(panelGame);
        panelParent.repaint();
        panelParent.revalidate();
        
        
        round=1;
    }//GEN-LAST:event_btnPlayActionPerformed
    
    public void sendFirst3Letters(char letter1,char letter2,char letter3){
        try(Socket socket= new Socket("localhost",5000)){
        
    //input, output reader 
            BufferedReader input= new BufferedReader(
            new InputStreamReader(socket.getInputStream()));
            
            PrintWriter output = new PrintWriter(socket.getOutputStream(),true);
                                                       
                output.println(letter1);
                output.println(letter2);
                output.println(letter3);
                
                
                
              //  String inputValue= input.readLine();
                
            
           
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }
    
    
    public void clearNames(){
        ArrayList<String> nameArray = new ArrayList<String>();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/glory_game", "root", "");
            
            
            PreparedStatement ps = conn.prepareStatement("SELECT name FROM playernames");
            ResultSet rs= ps.executeQuery();
            
            
            while(rs.next()){
                String tempName = rs.getString(1);
                nameArray.add(tempName);
            }
            
            if(nameArray.size()>1){
                Statement stmt= conn.createStatement();              
                stmt.executeUpdate("DELETE FROM playernames");       
            }
            
                 
            nameArray.clear();
        }
        catch(Exception e){
            System.out.println(e);
        }

    }
    
    public void passPlayerName(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/glory_game", "root", "");
            
            
            PreparedStatement ps = conn.prepareStatement("INSERT INTO playernames (name) Values (?)");
            ps.setString(1,playerName );
        
            int k=ps.executeUpdate();
            System.out.println("Player name added to database");
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }
    
    public void retreivePlayerNames(){
        ArrayList<String> nameArray = new ArrayList<String>();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/glory_game", "root", "");
            
            do{
                PreparedStatement ps = conn.prepareStatement("SELECT name FROM playernames");
                ResultSet rs= ps.executeQuery();
            
                nameArray.clear();
            while(rs.next()){
                String tempName = rs.getString(1);
                nameArray.add(tempName);
            }
            
            }while(nameArray.size()<=1);
            
            playerCount=nameArray.size();            
                       
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }
    
    
    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        playerName=txtPlayerName.getText();
        playerCount++;
        clearNames();
        passPlayerName();
        retreivePlayerNames();
        txtPlayersConnected.setText("Number of players connected - "+playerCount);
        txtPlayer1.setText(playerName);
        btnPlay.setEnabled(true);
    }//GEN-LAST:event_btnJoinActionPerformed
    
    public void generateFirst3Letters(){
        Random random = new Random();
        int letter1Index= random.nextInt(26);
        int letter2Index= random.nextInt(26);
        int letter3Index= random.nextInt(26);
        
        functionObj = new FunctionElement();
        functionObj.rarenessValueBank();
        char letter1=functionObj.valueList.get(letter1Index).getLetterName();
        char letter2=functionObj.valueList.get(letter2Index).getLetterName();
        char letter3=functionObj.valueList.get(letter3Index).getLetterName();
        
        p2Letter1.setText(String.valueOf(letter1));
        p2Letter2.setText(String.valueOf(letter2));
        p2Letter3.setText(String.valueOf(letter3));
    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHighScores;
    private javax.swing.JButton btnHowToPlay;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnP2_10C;
    private javax.swing.JButton btnP2_10V;
    private javax.swing.JButton btnP2_11C;
    private javax.swing.JButton btnP2_11V;
    private javax.swing.JButton btnP2_4C;
    private javax.swing.JButton btnP2_4V;
    private javax.swing.JButton btnP2_5C;
    private javax.swing.JButton btnP2_5V;
    private javax.swing.JButton btnP2_6C;
    private javax.swing.JButton btnP2_6V;
    private javax.swing.JButton btnP2_7C;
    private javax.swing.JButton btnP2_7V;
    private javax.swing.JButton btnP2_8C;
    private javax.swing.JButton btnP2_8V1;
    private javax.swing.JButton btnP2_9C;
    private javax.swing.JButton btnP2_9V;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlayNow;
    private javax.swing.JButton btnSubmitP2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblScoreP1;
    private javax.swing.JLabel lblScoreP2;
    private javax.swing.JLabel lblScoreP3;
    private javax.swing.JLabel lblScoreP4;
    private javax.swing.JLabel p1Letter1;
    private javax.swing.JLabel p1Letter10;
    private javax.swing.JLabel p1Letter11;
    private javax.swing.JLabel p1Letter12;
    private javax.swing.JLabel p1Letter13;
    private javax.swing.JLabel p1Letter14;
    private javax.swing.JLabel p1Letter15;
    private javax.swing.JLabel p1Letter16;
    private javax.swing.JLabel p1Letter17;
    private javax.swing.JLabel p1Letter18;
    private javax.swing.JLabel p1Letter19;
    private javax.swing.JLabel p1Letter2;
    private javax.swing.JLabel p1Letter20;
    private javax.swing.JLabel p1Letter21;
    private javax.swing.JLabel p1Letter22;
    private javax.swing.JLabel p1Letter23;
    private javax.swing.JLabel p1Letter24;
    private javax.swing.JLabel p1Letter25;
    private javax.swing.JLabel p1Letter26;
    private javax.swing.JLabel p1Letter27;
    private javax.swing.JLabel p1Letter28;
    private javax.swing.JLabel p1Letter29;
    private javax.swing.JLabel p1Letter3;
    private javax.swing.JLabel p1Letter30;
    private javax.swing.JLabel p1Letter31;
    private javax.swing.JLabel p1Letter32;
    private javax.swing.JLabel p1Letter33;
    private javax.swing.JLabel p1Letter34;
    private javax.swing.JLabel p1Letter37;
    private javax.swing.JLabel p1Letter39;
    private javax.swing.JLabel p1Letter4;
    private javax.swing.JLabel p1Letter5;
    private javax.swing.JLabel p1Letter6;
    private javax.swing.JLabel p1Letter7;
    private javax.swing.JLabel p1Letter8;
    private javax.swing.JLabel p1Letter9;
    private javax.swing.JLabel p2Letter1;
    private javax.swing.JLabel p2Letter10;
    private javax.swing.JLabel p2Letter11;
    private javax.swing.JLabel p2Letter2;
    private javax.swing.JLabel p2Letter3;
    private javax.swing.JLabel p2Letter4;
    private javax.swing.JLabel p2Letter5;
    private javax.swing.JLabel p2Letter6;
    private javax.swing.JLabel p2Letter7;
    private javax.swing.JLabel p2Letter8;
    private javax.swing.JLabel p2Letter9;
    private javax.swing.JPanel panelGame;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelStart;
    private javax.swing.JTextField txtFinalWordP2;
    private javax.swing.JLabel txtPlayer1;
    private javax.swing.JLabel txtPlayer2;
    private javax.swing.JTextField txtPlayerName;
    private javax.swing.JLabel txtPlayersConnected;
    // End of variables declaration//GEN-END:variables
}
