/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Glory_Schema;


import glory.game.server.InitialLetterDetails;
import glory.game.server.ScoreDetails;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

import java.util.ArrayList;
import java.util.Random;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


public class MainFrame extends javax.swing.JFrame {

    FunctionElement functionObj;
    int round=1;
    String playerName;
    int playerCount=0;
    int VCCount4,VCCount5,VCCount6,VCCount7,VCCount8,VCCount9,VCCount10,VCCount11=0;
    int finalScoreP1=0,finalScoreP2=0;
    
    DefaultTableModel model;
    String p2InitialLetters;
    String p1InitialLetters;
    ArrayList<String> allLetters;
    
    
    public MainFrame() {
        initComponents();
        
        panelParent.removeAll();
        panelParent.add(panelMain);
     // panelParent.add(panelGame);
        panelParent.repaint();
        panelParent.revalidate();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelParent = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        btnPlayNow = new javax.swing.JButton();
        btnHowToPlay = new javax.swing.JButton();
        btnHighScores = new javax.swing.JButton();
        lblVision = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelStart = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPlayerName = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnJoin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPlayersConnected = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JLabel();
        txtInfo = new javax.swing.JLabel();
        lblRound3 = new javax.swing.JLabel();
        lblRound4 = new javax.swing.JLabel();
        panelScoreCard = new javax.swing.JPanel();
        btnNextRound = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableScoreCard = new javax.swing.JTable();
        btnExitGame = new javax.swing.JButton();
        lblScorecardRound = new javax.swing.JLabel();
        lblScorecardRound1 = new javax.swing.JLabel();
        ScorecardPlayer2Score = new javax.swing.JLabel();
        ScorecardPlayer1Score = new javax.swing.JLabel();
        ScorecardPlayer2Score1 = new javax.swing.JLabel();
        ScorecardPlayer2Score3 = new javax.swing.JLabel();
        ScorecardPlayer2Score4 = new javax.swing.JLabel();
        panelGame = new javax.swing.JPanel();
        p2Letter1 = new javax.swing.JLabel();
        p2Letter2 = new javax.swing.JLabel();
        p2Letter3 = new javax.swing.JLabel();
        p2Letter4 = new javax.swing.JLabel();
        p2Letter5 = new javax.swing.JLabel();
        p2Letter6 = new javax.swing.JLabel();
        p2Letter7 = new javax.swing.JLabel();
        p2Letter8 = new javax.swing.JLabel();
        p2Letter9 = new javax.swing.JLabel();
        p2Letter10 = new javax.swing.JLabel();
        p2Letter11 = new javax.swing.JLabel();
        p2PlayerName = new javax.swing.JLabel();
        p1Letter2 = new javax.swing.JLabel();
        p1Letter3 = new javax.swing.JLabel();
        p1Letter4 = new javax.swing.JLabel();
        p1Letter5 = new javax.swing.JLabel();
        p1Letter6 = new javax.swing.JLabel();
        p1Letter7 = new javax.swing.JLabel();
        p1Letter8 = new javax.swing.JLabel();
        p1Letter9 = new javax.swing.JLabel();
        p1Letter10 = new javax.swing.JLabel();
        p1Letter11 = new javax.swing.JLabel();
        p1Letter1 = new javax.swing.JLabel();
        btnP2_8C = new javax.swing.JButton();
        btnP2_4V = new javax.swing.JButton();
        btnP2_4C = new javax.swing.JButton();
        btnP2_5V = new javax.swing.JButton();
        btnP2_5C = new javax.swing.JButton();
        btnP2_6V = new javax.swing.JButton();
        btnP2_6C = new javax.swing.JButton();
        btnP2_7V = new javax.swing.JButton();
        btnP2_7C = new javax.swing.JButton();
        btnP2_9V = new javax.swing.JButton();
        btnP2_9C = new javax.swing.JButton();
        btnP2_10V = new javax.swing.JButton();
        btnP2_10C = new javax.swing.JButton();
        btnP2_11V = new javax.swing.JButton();
        btnP2_11C = new javax.swing.JButton();
        p1PlayerName = new javax.swing.JLabel();
        lblRound = new javax.swing.JLabel();
        p1Letter39 = new javax.swing.JLabel();
        txtFinalWordP2 = new javax.swing.JTextField();
        lblScoreP1 = new javax.swing.JLabel();
        btnP2_8V = new javax.swing.JButton();
        btnSubmitP2 = new javax.swing.JButton();
        lblScoreP2 = new javax.swing.JLabel();
        btnChance = new javax.swing.JButton();
        btnWordGenerator = new javax.swing.JButton();
        p2Player = new javax.swing.JLabel();
        p2Player1 = new javax.swing.JLabel();
        lblRound1 = new javax.swing.JLabel();
        lblRound2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelParent.setMinimumSize(new java.awt.Dimension(0, 0));
        panelParent.setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(44, 62, 80));
        panelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPlayNow.setBackground(new java.awt.Color(44, 62, 80));
        btnPlayNow.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnPlayNow.setForeground(new java.awt.Color(236, 240, 241));
        btnPlayNow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/puzzle (1).png"))); // NOI18N
        btnPlayNow.setText(" Play Now");
        btnPlayNow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayNow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayNowActionPerformed(evt);
            }
        });
        panelMain.add(btnPlayNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 260, 286));

        btnHowToPlay.setBackground(new java.awt.Color(44, 62, 80));
        btnHowToPlay.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnHowToPlay.setForeground(new java.awt.Color(236, 240, 241));
        btnHowToPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/problems.png"))); // NOI18N
        btnHowToPlay.setText("How To PLay");
        btnHowToPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHowToPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMain.add(btnHowToPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 260, 286));

        btnHighScores.setBackground(new java.awt.Color(44, 62, 80));
        btnHighScores.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnHighScores.setForeground(new java.awt.Color(236, 240, 241));
        btnHighScores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/scoreboard.png"))); // NOI18N
        btnHighScores.setText("High Scores");
        btnHighScores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHighScores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelMain.add(btnHighScores, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 260, 286));

        lblVision.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVision.setForeground(new java.awt.Color(189, 195, 199));
        lblVision.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVision.setText("Unleash your word skills!");
        panelMain.add(lblVision, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 450, 50));

        jLabel2.setBackground(new java.awt.Color(52, 73, 94));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Glory Game");
        jLabel2.setOpaque(true);
        panelMain.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 140));

        panelParent.add(panelMain, "card3");

        panelStart.setBackground(new java.awt.Color(44, 62, 80));
        panelStart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(236, 240, 241));
        jSeparator2.setForeground(new java.awt.Color(236, 240, 241));
        panelStart.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, 370, 20));

        txtPlayerName.setBackground(new java.awt.Color(52, 73, 94));
        txtPlayerName.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtPlayerName.setForeground(new java.awt.Color(236, 240, 241));
        txtPlayerName.setBorder(null);
        txtPlayerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayerNameActionPerformed(evt);
            }
        });
        panelStart.add(txtPlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 360, 50));

        txtPlayer2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtPlayer2.setForeground(new java.awt.Color(236, 240, 241));
        panelStart.add(txtPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 420, 40));

        btnPlay.setBackground(new java.awt.Color(236, 240, 241));
        btnPlay.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(44, 62, 80));
        btnPlay.setText("Play Now");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        panelStart.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 590, 190, 40));

        jLabel3.setBackground(new java.awt.Color(52, 73, 94));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Glory Game");
        jLabel3.setOpaque(true);
        panelStart.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/chip (1).png"))); // NOI18N
        panelStart.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 560, 560));

        btnJoin.setBackground(new java.awt.Color(236, 240, 241));
        btnJoin.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnJoin.setForeground(new java.awt.Color(44, 62, 80));
        btnJoin.setText("Join In");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        panelStart.add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, 180, 40));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Player Name");
        panelStart.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 240, 50));

        txtPlayersConnected.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtPlayersConnected.setForeground(new java.awt.Color(236, 240, 241));
        txtPlayersConnected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlayersConnected.setText("Number of players connected - 0");
        panelStart.add(txtPlayersConnected, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 420, 50));

        txtPlayer1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        txtPlayer1.setForeground(new java.awt.Color(236, 240, 241));
        panelStart.add(txtPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 420, 40));

        txtInfo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtInfo.setForeground(new java.awt.Color(236, 240, 241));
        panelStart.add(txtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 660, 630, 30));

        lblRound3.setBackground(new java.awt.Color(52, 73, 94));
        lblRound3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRound3.setForeground(new java.awt.Color(236, 240, 241));
        lblRound3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRound3.setToolTipText("");
        lblRound3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 73, 94), 3, true));
        lblRound3.setOpaque(true);
        panelStart.add(lblRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 600, 270));

        lblRound4.setBackground(new java.awt.Color(52, 73, 94));
        lblRound4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRound4.setForeground(new java.awt.Color(236, 240, 241));
        lblRound4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRound4.setToolTipText("");
        lblRound4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 73, 94), 3, true));
        lblRound4.setOpaque(true);
        panelStart.add(lblRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 600, 180));

        panelParent.add(panelStart, "card4");

        panelScoreCard.setBackground(new java.awt.Color(44, 62, 80));
        panelScoreCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNextRound.setBackground(new java.awt.Color(236, 240, 241));
        btnNextRound.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnNextRound.setForeground(new java.awt.Color(44, 62, 80));
        btnNextRound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/keyboard-right-arrow-button (1).png"))); // NOI18N
        btnNextRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextRoundActionPerformed(evt);
            }
        });
        panelScoreCard.add(btnNextRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 610, 80, 50));

        jLabel6.setBackground(new java.awt.Color(52, 73, 94));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Glory Game");
        jLabel6.setOpaque(true);
        panelScoreCard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 140));

        tableScoreCard.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tableScoreCard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"hdvdv", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Player Name", "Round", "Rareness Score", "Reward Score", "Word Element Score", "Final Score"
            }
        ));
        tableScoreCard.setGridColor(new java.awt.Color(255, 255, 255));
        tableScoreCard.setName("Score Card"); // NOI18N
        tableScoreCard.setRowHeight(30);
        tableScoreCard.setSelectionBackground(new java.awt.Color(44, 62, 80));
        tableScoreCard.setSelectionForeground(new java.awt.Color(236, 240, 241));
        jScrollPane1.setViewportView(tableScoreCard);

        panelScoreCard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 940, 330));

        btnExitGame.setBackground(new java.awt.Color(236, 240, 241));
        btnExitGame.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnExitGame.setForeground(new java.awt.Color(44, 62, 80));
        btnExitGame.setText("Exit Game");
        btnExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitGameActionPerformed(evt);
            }
        });
        panelScoreCard.add(btnExitGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, 170, 40));

        lblScorecardRound.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblScorecardRound.setForeground(new java.awt.Color(189, 195, 199));
        lblScorecardRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScorecardRound.setText("Round");
        panelScoreCard.add(lblScorecardRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 450, 40));

        lblScorecardRound1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblScorecardRound1.setForeground(new java.awt.Color(236, 240, 241));
        lblScorecardRound1.setText("Current Scores");
        panelScoreCard.add(lblScorecardRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 450, 30));

        ScorecardPlayer2Score.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ScorecardPlayer2Score.setForeground(new java.awt.Color(189, 195, 199));
        ScorecardPlayer2Score.setText("Player 2-");
        panelScoreCard.add(ScorecardPlayer2Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 400, 30));

        ScorecardPlayer1Score.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ScorecardPlayer1Score.setForeground(new java.awt.Color(189, 195, 199));
        ScorecardPlayer1Score.setText("Player 1 -");
        panelScoreCard.add(ScorecardPlayer1Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 410, 30));

        ScorecardPlayer2Score1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ScorecardPlayer2Score1.setForeground(new java.awt.Color(189, 195, 199));
        ScorecardPlayer2Score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScorecardPlayer2Score1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/user (3).png"))); // NOI18N
        panelScoreCard.add(ScorecardPlayer2Score1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 60, 50));

        ScorecardPlayer2Score3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ScorecardPlayer2Score3.setForeground(new java.awt.Color(189, 195, 199));
        ScorecardPlayer2Score3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScorecardPlayer2Score3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/user (3).png"))); // NOI18N
        panelScoreCard.add(ScorecardPlayer2Score3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 60, 50));

        ScorecardPlayer2Score4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        ScorecardPlayer2Score4.setForeground(new java.awt.Color(189, 195, 199));
        ScorecardPlayer2Score4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScorecardPlayer2Score4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/scoreboard (2).png"))); // NOI18N
        panelScoreCard.add(ScorecardPlayer2Score4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 40, 30));

        panelParent.add(panelScoreCard, "card5");

        panelGame.setBackground(new java.awt.Color(44, 62, 80));
        panelGame.setMinimumSize(new java.awt.Dimension(1400, 700));
        panelGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2Letter1.setBackground(new java.awt.Color(130, 204, 221));
        p2Letter1.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter1.setText("A");
        p2Letter1.setOpaque(true);
        panelGame.add(p2Letter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 80, 80));

        p2Letter2.setBackground(new java.awt.Color(130, 204, 221));
        p2Letter2.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter2.setText("A");
        p2Letter2.setOpaque(true);
        panelGame.add(p2Letter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 80, 80));

        p2Letter3.setBackground(new java.awt.Color(130, 204, 221));
        p2Letter3.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter3.setText("A");
        p2Letter3.setOpaque(true);
        panelGame.add(p2Letter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 80, 80));

        p2Letter4.setBackground(new java.awt.Color(189, 195, 199));
        p2Letter4.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p2Letter4.setOpaque(true);
        panelGame.add(p2Letter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 80, 80));

        p2Letter5.setBackground(new java.awt.Color(189, 195, 199));
        p2Letter5.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p2Letter5.setOpaque(true);
        panelGame.add(p2Letter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 80, 80));

        p2Letter6.setBackground(new java.awt.Color(189, 195, 199));
        p2Letter6.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p2Letter6.setOpaque(true);
        panelGame.add(p2Letter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 80, 80));

        p2Letter7.setBackground(new java.awt.Color(189, 195, 199));
        p2Letter7.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p2Letter7.setOpaque(true);
        panelGame.add(p2Letter7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 80, 80));

        p2Letter8.setBackground(new java.awt.Color(189, 195, 199));
        p2Letter8.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p2Letter8.setOpaque(true);
        panelGame.add(p2Letter8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 80, 80));

        p2Letter9.setBackground(new java.awt.Color(189, 195, 199));
        p2Letter9.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p2Letter9.setOpaque(true);
        panelGame.add(p2Letter9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 400, 80, 80));

        p2Letter10.setBackground(new java.awt.Color(189, 195, 199));
        p2Letter10.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p2Letter10.setOpaque(true);
        panelGame.add(p2Letter10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, 80, 80));

        p2Letter11.setBackground(new java.awt.Color(189, 195, 199));
        p2Letter11.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p2Letter11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2Letter11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p2Letter11.setOpaque(true);
        panelGame.add(p2Letter11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 400, 80, 80));

        p2PlayerName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p2PlayerName.setForeground(new java.awt.Color(236, 240, 241));
        p2PlayerName.setText("PLAYER 2 : Zacky");
        panelGame.add(p2PlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 310, 40));

        p1Letter2.setBackground(new java.awt.Color(130, 204, 221));
        p1Letter2.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter2.setText("A");
        p1Letter2.setOpaque(true);
        panelGame.add(p1Letter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 80, 80));

        p1Letter3.setBackground(new java.awt.Color(130, 204, 221));
        p1Letter3.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter3.setText("A");
        p1Letter3.setOpaque(true);
        panelGame.add(p1Letter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 80, 80));

        p1Letter4.setBackground(new java.awt.Color(189, 195, 199));
        p1Letter4.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/questions-circular-button.png"))); // NOI18N
        p1Letter4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p1Letter4.setOpaque(true);
        panelGame.add(p1Letter4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 80, 80));

        p1Letter5.setBackground(new java.awt.Color(189, 195, 199));
        p1Letter5.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/questions-circular-button.png"))); // NOI18N
        p1Letter5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p1Letter5.setOpaque(true);
        panelGame.add(p1Letter5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 80, 80));

        p1Letter6.setBackground(new java.awt.Color(189, 195, 199));
        p1Letter6.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/questions-circular-button.png"))); // NOI18N
        p1Letter6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p1Letter6.setOpaque(true);
        panelGame.add(p1Letter6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 80, 80));

        p1Letter7.setBackground(new java.awt.Color(189, 195, 199));
        p1Letter7.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/questions-circular-button.png"))); // NOI18N
        p1Letter7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p1Letter7.setOpaque(true);
        panelGame.add(p1Letter7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 80, 80));

        p1Letter8.setBackground(new java.awt.Color(189, 195, 199));
        p1Letter8.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/questions-circular-button.png"))); // NOI18N
        p1Letter8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p1Letter8.setOpaque(true);
        panelGame.add(p1Letter8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 80, 80));

        p1Letter9.setBackground(new java.awt.Color(189, 195, 199));
        p1Letter9.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/questions-circular-button.png"))); // NOI18N
        p1Letter9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p1Letter9.setOpaque(true);
        panelGame.add(p1Letter9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 80, 80));

        p1Letter10.setBackground(new java.awt.Color(189, 195, 199));
        p1Letter10.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/questions-circular-button.png"))); // NOI18N
        p1Letter10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p1Letter10.setOpaque(true);
        panelGame.add(p1Letter10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, 80, 80));

        p1Letter11.setBackground(new java.awt.Color(189, 195, 199));
        p1Letter11.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Glory_Schema/questions-circular-button.png"))); // NOI18N
        p1Letter11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 240, 241), 2, true));
        p1Letter11.setOpaque(true);
        panelGame.add(p1Letter11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 150, 80, 80));

        p1Letter1.setBackground(new java.awt.Color(130, 204, 221));
        p1Letter1.setFont(new java.awt.Font("Century Gothic", 0, 50)); // NOI18N
        p1Letter1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter1.setText("A");
        p1Letter1.setOpaque(true);
        panelGame.add(p1Letter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 80, 80));

        btnP2_8C.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_8C.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_8C.setText("C");
        btnP2_8C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_8CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_8C, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 70, 40));

        btnP2_4V.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_4V.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_4V.setText("V");
        btnP2_4V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_4VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_4V, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 70, -1));

        btnP2_4C.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_4C.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_4C.setText("C");
        btnP2_4C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_4CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_4C, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 70, 40));

        btnP2_5V.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_5V.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_5V.setText("V");
        btnP2_5V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_5VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_5V, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 70, 40));

        btnP2_5C.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_5C.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_5C.setText("C");
        btnP2_5C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_5CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_5C, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 70, 40));

        btnP2_6V.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_6V.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_6V.setText("V");
        btnP2_6V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_6VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_6V, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 70, 40));

        btnP2_6C.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_6C.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_6C.setText("C");
        btnP2_6C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_6CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_6C, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 70, 40));

        btnP2_7V.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_7V.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_7V.setText("V");
        btnP2_7V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_7VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_7V, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 70, 40));

        btnP2_7C.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_7C.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_7C.setText("C");
        btnP2_7C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_7CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_7C, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, 70, 40));

        btnP2_9V.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_9V.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_9V.setText("V");
        btnP2_9V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_9VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_9V, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, 70, 40));

        btnP2_9C.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_9C.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_9C.setText("C");
        btnP2_9C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_9CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_9C, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, 70, 40));

        btnP2_10V.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_10V.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_10V.setText("V");
        btnP2_10V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_10VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_10V, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 500, 70, 40));

        btnP2_10C.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_10C.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_10C.setText("C");
        btnP2_10C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_10CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_10C, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 560, 70, 40));

        btnP2_11V.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_11V.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_11V.setText("V");
        btnP2_11V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_11VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_11V, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 500, 70, 40));

        btnP2_11C.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_11C.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_11C.setText("C");
        btnP2_11C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_11CActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_11C, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 560, 70, 40));

        p1PlayerName.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        p1PlayerName.setForeground(new java.awt.Color(236, 240, 241));
        p1PlayerName.setText("PLAYER 1 : Adam");
        panelGame.add(p1PlayerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, 40));

        lblRound.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblRound.setForeground(new java.awt.Color(236, 240, 241));
        lblRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRound.setText("Round : 1");
        lblRound.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        panelGame.add(lblRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 130, 40));

        p1Letter39.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        p1Letter39.setForeground(new java.awt.Color(236, 240, 241));
        p1Letter39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1Letter39.setText("Final Word");
        panelGame.add(p1Letter39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 160, 30));

        txtFinalWordP2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtFinalWordP2.setToolTipText("Final Word");
        txtFinalWordP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalWordP2ActionPerformed(evt);
            }
        });
        panelGame.add(txtFinalWordP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 310, 30));

        lblScoreP1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblScoreP1.setForeground(new java.awt.Color(236, 240, 241));
        lblScoreP1.setText("Score : 0");
        panelGame.add(lblScoreP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        btnP2_8V.setBackground(new java.awt.Color(236, 240, 241));
        btnP2_8V.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnP2_8V.setText("V");
        btnP2_8V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2_8VActionPerformed(evt);
            }
        });
        panelGame.add(btnP2_8V, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 70, 40));

        btnSubmitP2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnSubmitP2.setText("Submit");
        btnSubmitP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitP2ActionPerformed(evt);
            }
        });
        panelGame.add(btnSubmitP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, 100, 30));

        lblScoreP2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblScoreP2.setForeground(new java.awt.Color(236, 240, 241));
        lblScoreP2.setText("Score : 0");
        panelGame.add(lblScoreP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, 30));

        btnChance.setBackground(new java.awt.Color(204, 204, 204));
        btnChance.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnChance.setText("Chance");
        btnChance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChanceActionPerformed(evt);
            }
        });
        panelGame.add(btnChance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 620, 110, 50));

        btnWordGenerator.setBackground(new java.awt.Color(204, 204, 204));
        btnWordGenerator.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnWordGenerator.setText("Word Generator");
        btnWordGenerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWordGeneratorActionPerformed(evt);
            }
        });
        panelGame.add(btnWordGenerator, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 620, 140, 50));

        p2Player.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        p2Player.setForeground(new java.awt.Color(236, 240, 241));
        p2Player.setText("PLAYER 1 - ");
        panelGame.add(p2Player, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        p2Player1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        p2Player1.setForeground(new java.awt.Color(236, 240, 241));
        p2Player1.setText("PLAYER 2 - ");
        panelGame.add(p2Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 40));

        lblRound1.setBackground(new java.awt.Color(52, 73, 94));
        lblRound1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRound1.setForeground(new java.awt.Color(236, 240, 241));
        lblRound1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRound1.setToolTipText("");
        lblRound1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 73, 94), 3, true));
        lblRound1.setOpaque(true);
        panelGame.add(lblRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 350, 110));

        lblRound2.setBackground(new java.awt.Color(52, 73, 94));
        lblRound2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRound2.setForeground(new java.awt.Color(236, 240, 241));
        lblRound2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRound2.setToolTipText("");
        lblRound2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(52, 73, 94), 3, true));
        lblRound2.setOpaque(true);
        panelGame.add(lblRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 110));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("43");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel1.setOpaque(true);
        panelGame.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 130, 90));

        panelParent.add(panelGame, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnP2_8CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_8CActionPerformed
        VCCount8++;
        
        char consonant=functionObj.generateConsonant();
        p2Letter8.setText(String.valueOf(consonant));
        
        btnP2_8C.setEnabled(false);
        btnP2_8V.setEnabled(false);
        btnP2_9V.setEnabled(true);
        btnP2_9C.setEnabled(true);
        if(VCCount8==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }    
        
    }//GEN-LAST:event_btnP2_8CActionPerformed

    private void btnP2_4CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_4CActionPerformed
        VCCount4++;
        
        char consonant=functionObj.generateConsonant();
        p2Letter4.setText(String.valueOf(consonant));
        
        btnP2_4C.setEnabled(false);
        btnP2_4V.setEnabled(false);
        btnP2_5V.setEnabled(true);
        btnP2_5C.setEnabled(true);
        if(VCCount4==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
        
    }//GEN-LAST:event_btnP2_4CActionPerformed

    private void btnP2_5CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_5CActionPerformed
        VCCount5++;
        
        char consonant=functionObj.generateConsonant();
        p2Letter5.setText(String.valueOf(consonant));
        
        btnP2_5C.setEnabled(false);
        btnP2_5V.setEnabled(false);
        btnP2_6V.setEnabled(true);
        btnP2_6C.setEnabled(true);
        if(VCCount5==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
        
    }//GEN-LAST:event_btnP2_5CActionPerformed

    private void btnP2_6CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_6CActionPerformed
        VCCount6++;
        
        char consonant=functionObj.generateConsonant();
        p2Letter6.setText(String.valueOf(consonant));
        
        btnP2_6C.setEnabled(false);
        btnP2_6V.setEnabled(false);
        btnP2_7V.setEnabled(true);
        btnP2_7C.setEnabled(true);
        if(VCCount6==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
        
    }//GEN-LAST:event_btnP2_6CActionPerformed

    private void btnP2_7CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_7CActionPerformed
        VCCount7++;
        
        char consonant=functionObj.generateConsonant();
        p2Letter7.setText(String.valueOf(consonant));
        
        btnP2_7C.setEnabled(false);
        btnP2_7V.setEnabled(false);
        btnP2_8V.setEnabled(true);
        btnP2_8C.setEnabled(true);
        if(VCCount7==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
        
    }//GEN-LAST:event_btnP2_7CActionPerformed

    private void btnP2_9CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_9CActionPerformed
        VCCount9++;
        
        char consonant=functionObj.generateConsonant();
        p2Letter9.setText(String.valueOf(consonant));
        
        btnP2_9C.setEnabled(false);
        btnP2_9V.setEnabled(false);
        btnP2_10V.setEnabled(true);
        btnP2_10C.setEnabled(true);
        if(VCCount9==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
        
    }//GEN-LAST:event_btnP2_9CActionPerformed

    private void btnP2_10CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_10CActionPerformed
        VCCount10++;
        
        char consonant=functionObj.generateConsonant();
        p2Letter10.setText(String.valueOf(consonant));
        
        btnP2_10C.setEnabled(false);
        btnP2_10V.setEnabled(false);
        btnP2_11V.setEnabled(true);
        btnP2_11C.setEnabled(true);
        if(VCCount10==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
        
    }//GEN-LAST:event_btnP2_10CActionPerformed

    private void btnP2_11CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_11CActionPerformed
        VCCount11++;
        
        char consonant=functionObj.generateConsonant();
        p2Letter11.setText(String.valueOf(consonant));
        
        btnP2_11C.setEnabled(false);
        btnP2_11V.setEnabled(false);
        btnSubmitP2.setEnabled(true);
        btnChance.setEnabled(true);
        Color chanceOn = new Color(85,239,196);
        btnChance.setBackground(chanceOn);
        if(VCCount11==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
        
    }//GEN-LAST:event_btnP2_11CActionPerformed

    private void txtFinalWordP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalWordP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinalWordP2ActionPerformed

    private void btnSubmitP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitP2ActionPerformed
        String UserFinalWord, validityWithDictionary,ValidityWithGivenWords;
        UserFinalWord=txtFinalWordP2.getText();
        
        //make final word available to all child classes of GloryElement
        GloryElement wordObj = new GloryElement();
        wordObj.setFinalWord(UserFinalWord);
        wordObj.setFinalWordLength();
        
        //check if its a valid word in dictionary
        Dictionary dObj = new Dictionary(UserFinalWord,"manual");
        validityWithDictionary= dObj.getValidity();
         
        functionObj = new FunctionElement();
    //check if its made out of the given words
        generateAllLetters();
        ValidityWithGivenWords= functionObj.checkValidityWithDisplayedLetters(allLetters);
        
        functionObj.generateScore(validityWithDictionary,ValidityWithGivenWords);
       
        ServerElement serverObj = new ServerElement(playerName,round, functionObj.rarenessScore, functionObj.rewardScore, functionObj.wordLengthScore, functionObj.RoundScore);
        
        panelParent.removeAll();
        panelParent.add(panelScoreCard);
        panelParent.repaint();
        panelParent.revalidate();
        
        fillScoreCard();
        
        if(round==5){
            btnNextRound.setVisible(false);
            btnExitGame.setVisible(true);
        }
        
         
    }//GEN-LAST:event_btnSubmitP2ActionPerformed

    private void btnP2_4VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_4VActionPerformed
        VCCount4++;
        
        char vowel=functionObj.generateVowel();
        p2Letter4.setText(String.valueOf(vowel));
        
        btnP2_4V.setEnabled(false);
        btnP2_4C.setEnabled(false);
        btnP2_5V.setEnabled(true);
        btnP2_5C.setEnabled(true);
        if(VCCount4==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
        
    }//GEN-LAST:event_btnP2_4VActionPerformed

    private void btnP2_5VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_5VActionPerformed
        VCCount5++;
        
        char vowel=functionObj.generateVowel();
        p2Letter5.setText(String.valueOf(vowel));
        
        btnP2_5V.setEnabled(false);
        btnP2_5C.setEnabled(false);
        btnP2_6V.setEnabled(true);
        btnP2_6C.setEnabled(true);
        if(VCCount5==2){
            disEnableVowelConsonentButtons();
            Color chanceOff = new Color(255,118,117);
            btnChance.setBackground(chanceOff);
        }
    }//GEN-LAST:event_btnP2_5VActionPerformed

    private void btnP2_6VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_6VActionPerformed
        VCCount6++;
        
        char vowel=functionObj.generateVowel();
        p2Letter6.setText(String.valueOf(vowel));
        
        btnP2_6V.setEnabled(false);
        btnP2_6C.setEnabled(false);
        btnP2_7V.setEnabled(true);
        btnP2_7C.setEnabled(true);
        if(VCCount6==2){
            disEnableVowelConsonentButtons();
        }
    }//GEN-LAST:event_btnP2_6VActionPerformed

    private void btnP2_7VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_7VActionPerformed
        VCCount7++;
        
        char vowel=functionObj.generateVowel();
        p2Letter7.setText(String.valueOf(vowel));
        
        btnP2_7V.setEnabled(false);
        btnP2_7C.setEnabled(false);
        btnP2_8V.setEnabled(true);
        btnP2_8C.setEnabled(true);
        if(VCCount7==2){
            disEnableVowelConsonentButtons();
        }
        
    }//GEN-LAST:event_btnP2_7VActionPerformed

    private void btnP2_8VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_8VActionPerformed
        VCCount8++;
        
        char vowel=functionObj.generateVowel();
        p2Letter8.setText(String.valueOf(vowel));
        
        btnP2_8V.setEnabled(false);
        btnP2_8C.setEnabled(false);
        btnP2_9V.setEnabled(true);
        btnP2_9C.setEnabled(true);
        if(VCCount8==2){
            disEnableVowelConsonentButtons();
        }
        
    }//GEN-LAST:event_btnP2_8VActionPerformed

    private void btnP2_9VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_9VActionPerformed
        VCCount9++;
        
        char vowel=functionObj.generateVowel();
        p2Letter9.setText(String.valueOf(vowel));
        
        btnP2_9V.setEnabled(false);
        btnP2_9C.setEnabled(false);
        btnP2_10V.setEnabled(true);
        btnP2_10C.setEnabled(true);
        if(VCCount9==2){
            disEnableVowelConsonentButtons();
        }
        
    }//GEN-LAST:event_btnP2_9VActionPerformed

    private void btnP2_10VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_10VActionPerformed
        VCCount10++;
        
        char vowel=functionObj.generateVowel();
        p2Letter10.setText(String.valueOf(vowel));
        
        btnP2_10V.setEnabled(false);
        btnP2_10C.setEnabled(false);
        btnP2_11V.setEnabled(true);
        btnP2_11C.setEnabled(true);
        if(VCCount10==2){
            disEnableVowelConsonentButtons();
        }
        
    }//GEN-LAST:event_btnP2_10VActionPerformed

    private void btnP2_11VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2_11VActionPerformed
        VCCount11++;
        
        char vowel=functionObj.generateVowel();
        p2Letter11.setText(String.valueOf(vowel));
        
        btnP2_11V.setEnabled(false);
        btnP2_11C.setEnabled(false);
        btnSubmitP2.setEnabled(true);
        btnChance.setEnabled(true);
        Color chanceOn = new Color(85,239,196);
        btnChance.setBackground(chanceOn);
        if(VCCount11==2){
            disEnableVowelConsonentButtons();
        }
        
    }//GEN-LAST:event_btnP2_11VActionPerformed

    private void btnPlayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayNowActionPerformed
        panelParent.removeAll();
        panelParent.add(panelStart);
        panelParent.repaint();
        panelParent.revalidate();
        
        clearStartMenueData();
        btnPlay.setVisible(false);
    
    }//GEN-LAST:event_btnPlayNowActionPerformed

    private void txtPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerNameActionPerformed
        
    }//GEN-LAST:event_txtPlayerNameActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        panelParent.removeAll();
        panelParent.add(panelGame);
        panelParent.repaint();
        panelParent.revalidate();
                
        round=1;
        generateFirst3Letters();
        getAndSendInitialLetters();
        displayOpponentsInitialLetters();
        
        disEnableVowelConsonentButtons();
        btnExitGame.setVisible(false);
        btnP2_4V.setEnabled(true);
        btnP2_4C.setEnabled(true);
        btnSubmitP2.setEnabled(false);
        btnChance.setEnabled(false);
        
        
    }//GEN-LAST:event_btnPlayActionPerformed
    
    public void fillScoreCard(){
        ArrayList<ScoreDetails> container = new ArrayList<ScoreDetails>() ;
        
        
        ServerElement obj = new ServerElement();
        container=obj.getScoreContainer();
        
        model = (DefaultTableModel)tableScoreCard.getModel();
        model.setRowCount(0);
        
        JTableHeader header = tableScoreCard.getTableHeader();
        header.setFont(new Font ("Century Gothic",Font.PLAIN,18));
        Object[] row = new Object[6];
        
        for(int j=0;j<container.size();j++){
            
            row[0]= container.get(j).getPlayerName();  
            row[1]= String.valueOf(container.get(j).getRound());
            row[2]= String.valueOf(container.get(j).getRarenessScore());
            row[3]= String.valueOf(container.get(j).getRewardScore());
            row[4]= String.valueOf(container.get(j).getWordLengthScore());
            row[5]= String.valueOf(container.get(j).getFinalScore());
            
        model.addRow(row); 
        }
        
        int containerSize = container.size();
        int currentRound = container.get(containerSize-1).getRound();
        lblScorecardRound.setText("End of round "+String.valueOf(currentRound));
        
        String p1=p1PlayerName.getText();
        String p2=p2PlayerName.getText();
        int size= container.size();
        if(container.get(size-1).getPlayerName().equals(p1)){
            finalScoreP1+=container.get(size-1).getFinalScore();
            finalScoreP2+=container.get(size-2).getFinalScore();
        }
        else if(container.get(size-1).getPlayerName().equals(p2)){
            finalScoreP2+=container.get(size-1).getFinalScore();
            finalScoreP1+=container.get(size-2).getFinalScore();
        }
        lblScoreP1.setText("Score - "+finalScoreP1);
        lblScoreP2.setText("Score - "+finalScoreP2);
        
        ScorecardPlayer1Score.setText(p1+" - "+finalScoreP1);
        ScorecardPlayer2Score.setText(p2+" - "+finalScoreP2);
    }
    
    
    public void sendFirst3Letters(char letter1,char letter2,char letter3){
        try(Socket socket= new Socket("localhost",5000)){
        
    //input, output reader 
            BufferedReader input= new BufferedReader(
            new InputStreamReader(socket.getInputStream()));
            
            PrintWriter output = new PrintWriter(socket.getOutputStream(),true);
                                                       
                output.println(letter1);
                output.println(letter2);
                output.println(letter3);
                
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }
    
    
    
    
    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        playerName=txtPlayerName.getText();
            
        NameElements NEObj= new NameElements(playerName);
        
        displayPlayersToStartScreen();
        
        btnPlay.setVisible(true);
        btnJoin.setEnabled(false);
        txtInfo.setText("You will be taken to the game when you and your opponent are ready!");
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnNextRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextRoundActionPerformed
         round++;
         
        panelParent.removeAll();
        panelParent.add(panelGame);
        panelParent.repaint();
        panelParent.revalidate();
        
        generateFirst3Letters();
        getAndSendInitialLetters();
        displayOpponentsInitialLetters();

        clearOtherLetters();
        VCCount4=0; VCCount5=0; VCCount6=0; VCCount7=0; VCCount8=0; VCCount9=0; VCCount10=0; VCCount11=0;
        disEnableVowelConsonentButtons();
        btnP2_4V.setEnabled(true);
        btnP2_4C.setEnabled(true);
        btnSubmitP2.setEnabled(false);
        btnChance.setEnabled(false);
        Color chanceDefault = new Color(204,204,204);
        btnChance.setBackground(chanceDefault);
    }//GEN-LAST:event_btnNextRoundActionPerformed

    private void btnExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitGameActionPerformed
        panelParent.removeAll();
        panelParent.add(panelMain);
        panelParent.repaint();
        panelParent.revalidate();
        
        clearStartMenueData();
    }//GEN-LAST:event_btnExitGameActionPerformed

    private void btnChanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChanceActionPerformed
        enableVowelConsonentButtons();
        Color chanceOff = new Color(255,118,117);
        btnChance.setBackground(chanceOff);
        btnChance.setEnabled(false);
    }//GEN-LAST:event_btnChanceActionPerformed

    private void btnWordGeneratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWordGeneratorActionPerformed
        String word="";
        generateAllLetters();
        for(int i=0;i<allLetters.size();i++){
            word+=allLetters.get(i);
        }
        
        Dictionary dObj = new Dictionary(word,"automatic");
    }//GEN-LAST:event_btnWordGeneratorActionPerformed
    
    public void generateFirst3Letters(){
        Random random = new Random();
        int letter1Index= random.nextInt(26);
        int letter2Index= random.nextInt(26);
        int letter3Index= random.nextInt(26);
        
        functionObj = new FunctionElement();
        functionObj.rarenessValueBank();
        char letter1=functionObj.valueList.get(letter1Index).getLetterName();
        char letter2=functionObj.valueList.get(letter2Index).getLetterName();
        char letter3=functionObj.valueList.get(letter3Index).getLetterName();
        
        p2Letter1.setText(String.valueOf(letter1));
        p2Letter2.setText(String.valueOf(letter2));
        p2Letter3.setText(String.valueOf(letter3));
    }
    
    public void generateAllLetters(){  
        allLetters = new ArrayList<String>();
        allLetters.clear();
        
        allLetters.add(p2Letter1.getText());
        allLetters.add(p2Letter2.getText());
        allLetters.add(p2Letter3.getText());
        allLetters.add(p2Letter4.getText());
        allLetters.add(p2Letter5.getText());
        allLetters.add(p2Letter6.getText());
        allLetters.add(p2Letter7.getText());
        allLetters.add(p2Letter8.getText());
        allLetters.add(p2Letter9.getText());
        allLetters.add(p2Letter10.getText());
        allLetters.add(p2Letter11.getText());
        
        
        
        
    }
    public void getAndSendInitialLetters(){
        String letter1=p2Letter1.getText();
        String letter2=p2Letter2.getText();
        String letter3=p2Letter3.getText();
        p2InitialLetters=letter1+letter2+letter3;
        
        InitialLetters initialObj = new InitialLetters(p2InitialLetters,round,playerName);
    }
    
    
    public void displayOpponentsInitialLetters(){
        ArrayList<InitialLetterDetails> iLContainer = new ArrayList<InitialLetterDetails>();
        InitialLetters iLObj = new InitialLetters();
     
        iLContainer=iLObj.initialLettersContainerClient;
        
        int size=iLContainer.size();
        String iL1=iLContainer.get(size-2).getInitialLetters();
        String iL2=iLContainer.get(size-1).getInitialLetters();
        
        
        
        if(p2InitialLetters.equals(iL1)){
            p1InitialLetters=iL2;
            String p1=iLContainer.get(size-1).getPlayerName();
            p1PlayerName.setText(p1);
            String p2=iLContainer.get(size-2).getPlayerName();
            p2PlayerName.setText(p2);
    
        }
        if(!p2InitialLetters.equals(iL1)){
            p1InitialLetters=iL1;
            String p1=iLContainer.get(size-2).getPlayerName();
            p1PlayerName.setText(p1);
            String p2=iLContainer.get(size-1).getPlayerName();
            p2PlayerName.setText(p2);
        }
        char l1=p1InitialLetters.charAt(0);
        char l2=p1InitialLetters.charAt(1);
        char l3=p1InitialLetters.charAt(2);
        
        p1Letter1.setText(String.valueOf(l1));
        p1Letter2.setText(String.valueOf(l2));
        p1Letter3.setText(String.valueOf(l3));
        String round= "Round "+String.valueOf(iLContainer.get(size-1).getRound());
        lblRound.setText(round);
        iLContainer.clear();
    }
    
    public void clearOtherLetters(){
        p2Letter4.setText("");
        p2Letter5.setText("");
        p2Letter6.setText("");
        p2Letter7.setText("");
        p2Letter8.setText("");
        p2Letter9.setText("");
        p2Letter10.setText("");
        p2Letter11.setText("");
        txtFinalWordP2.setText("");
        
    }
    
    public void clearStartMenueData(){
        txtPlayerName.setText("");
        txtPlayersConnected.setText("Number of players connected - 0");
        txtPlayer1.setText("");
        txtPlayer2.setText("");
    }
    
    public void displayPlayersToStartScreen(){
        ArrayList<String> container = new ArrayList<String>();
        NameElements nameObj = new NameElements();
        container=nameObj.nameContainerClient;
        
        playerCount=container.size();
        String player1 = container.get(0);
        String player2= container.get(1);
        
        txtPlayersConnected.setText("Number of players connected - "+playerCount);
        txtPlayer1.setText("Player 1 - "+player1);
        txtPlayer2.setText("Player 2 - "+player2);
        
    }
    
    public void enableVowelConsonentButtons(){
        btnP2_4V.setEnabled(true);
        btnP2_4C.setEnabled(true);
        
        btnP2_5V.setEnabled(true);
        btnP2_5C.setEnabled(true);
        
        btnP2_6V.setEnabled(true);
        btnP2_6C.setEnabled(true);
        
        btnP2_7V.setEnabled(true);
        btnP2_7C.setEnabled(true);
        
        btnP2_8V.setEnabled(true);
        btnP2_8C.setEnabled(true);
        
        btnP2_9V.setEnabled(true);
        btnP2_9C.setEnabled(true);
        
        btnP2_10V.setEnabled(true);
        btnP2_10C.setEnabled(true);
        
        btnP2_11V.setEnabled(true);
        btnP2_11C.setEnabled(true);
        
    }
    
    public void disEnableVowelConsonentButtons(){
        btnP2_4V.setEnabled(false);
        btnP2_4C.setEnabled(false);
        
        btnP2_5V.setEnabled(false);
        btnP2_5C.setEnabled(false);
        
        btnP2_6V.setEnabled(false);
        btnP2_6C.setEnabled(false);
        
        btnP2_7V.setEnabled(false);
        btnP2_7C.setEnabled(false);
        
        btnP2_8V.setEnabled(false);
        btnP2_8C.setEnabled(false);
        
        btnP2_9V.setEnabled(false);
        btnP2_9C.setEnabled(false);
        
        btnP2_10V.setEnabled(false);
        btnP2_10C.setEnabled(false);
        
        btnP2_11V.setEnabled(false);
        btnP2_11C.setEnabled(false);
        
    }
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ScorecardPlayer1Score;
    private javax.swing.JLabel ScorecardPlayer2Score;
    private javax.swing.JLabel ScorecardPlayer2Score1;
    private javax.swing.JLabel ScorecardPlayer2Score3;
    private javax.swing.JLabel ScorecardPlayer2Score4;
    private javax.swing.JButton btnChance;
    private javax.swing.JButton btnExitGame;
    private javax.swing.JButton btnHighScores;
    private javax.swing.JButton btnHowToPlay;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnNextRound;
    private javax.swing.JButton btnP2_10C;
    private javax.swing.JButton btnP2_10V;
    private javax.swing.JButton btnP2_11C;
    private javax.swing.JButton btnP2_11V;
    private javax.swing.JButton btnP2_4C;
    private javax.swing.JButton btnP2_4V;
    private javax.swing.JButton btnP2_5C;
    private javax.swing.JButton btnP2_5V;
    private javax.swing.JButton btnP2_6C;
    private javax.swing.JButton btnP2_6V;
    private javax.swing.JButton btnP2_7C;
    private javax.swing.JButton btnP2_7V;
    private javax.swing.JButton btnP2_8C;
    private javax.swing.JButton btnP2_8V;
    private javax.swing.JButton btnP2_9C;
    private javax.swing.JButton btnP2_9V;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlayNow;
    private javax.swing.JButton btnSubmitP2;
    private javax.swing.JButton btnWordGenerator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel lblRound1;
    private javax.swing.JLabel lblRound2;
    private javax.swing.JLabel lblRound3;
    private javax.swing.JLabel lblRound4;
    private javax.swing.JLabel lblScoreP1;
    private javax.swing.JLabel lblScoreP2;
    private javax.swing.JLabel lblScorecardRound;
    private javax.swing.JLabel lblScorecardRound1;
    private javax.swing.JLabel lblVision;
    private javax.swing.JLabel p1Letter1;
    private javax.swing.JLabel p1Letter10;
    private javax.swing.JLabel p1Letter11;
    private javax.swing.JLabel p1Letter2;
    private javax.swing.JLabel p1Letter3;
    private javax.swing.JLabel p1Letter39;
    private javax.swing.JLabel p1Letter4;
    private javax.swing.JLabel p1Letter5;
    private javax.swing.JLabel p1Letter6;
    private javax.swing.JLabel p1Letter7;
    private javax.swing.JLabel p1Letter8;
    private javax.swing.JLabel p1Letter9;
    private javax.swing.JLabel p1PlayerName;
    private javax.swing.JLabel p2Letter1;
    private javax.swing.JLabel p2Letter10;
    private javax.swing.JLabel p2Letter11;
    private javax.swing.JLabel p2Letter2;
    private javax.swing.JLabel p2Letter3;
    private javax.swing.JLabel p2Letter4;
    private javax.swing.JLabel p2Letter5;
    private javax.swing.JLabel p2Letter6;
    private javax.swing.JLabel p2Letter7;
    private javax.swing.JLabel p2Letter8;
    private javax.swing.JLabel p2Letter9;
    private javax.swing.JLabel p2Player;
    private javax.swing.JLabel p2Player1;
    private javax.swing.JLabel p2PlayerName;
    private javax.swing.JPanel panelGame;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelParent;
    private javax.swing.JPanel panelScoreCard;
    private javax.swing.JPanel panelStart;
    private javax.swing.JTable tableScoreCard;
    private javax.swing.JTextField txtFinalWordP2;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtPlayer1;
    private javax.swing.JLabel txtPlayer2;
    private javax.swing.JTextField txtPlayerName;
    private javax.swing.JLabel txtPlayersConnected;
    // End of variables declaration//GEN-END:variables
}
